# Include the nojekyll in output
include:
  - .nojekyll

# Files/Folders to exclude from the final output
exclude:
  - config.rb
  - .sass-cache

# Enable Pagination, because we're awesome like that
paginate: 8
paginate_path: page/:num

# And building into custom directory
destination: ../danneh.github.com.production/_site

pygments: true
markdown: rdiscount
